spring.application.name=vehicle parking management system
server.port=8080

#csv file path
parknow.data.users=src/main/resources/data/users.csv
parknow.data.vehicles=src/main/resources/data/vehicles.csv
parknow.data.slots=src/main/resources/data/slots.csv
parknow.data.reservations=src/main/resources/data/reservations.csv
parknow.data.feedback=src/main/resources/data/feedbacks.csv
parknow.data.admins=src/main/resources/data/admins.csv

parknow.data.activity-log=default_activity.log

parknow.slots.total-count=30
parknow.rate.default=150.0
